language: go

go:
    - 1.9
    - master

matrix:
    allow_failures:
        - go: master

script:
    - make travis -j 8

notifications:
    email: false
    webhooks:
        urls:
            - https://lism.in/travis
        on_success: always
        on_failure: always
        on_start: always
